<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Добавление животного</title>
</head>
<body>
<form action="/created" method="post">
    <input name="name" placeholder="Мурка"><br>
    <input name="description" placeholder="Бодрая, красивая, нежная"><br>
    <input type="text" name="age" placeholder="2 года"><br>
    <input type="text" name="img" placeholder="img"><br>
    <input type="text" name="sex" placeholder="девочка/мальчик"><br>
    <input type="text" name="breed" placeholder="порода - бигль"><br>
    <input type="text" name="disease" placeholder="болезни отсутствуют"><br>
    <input type="submit" value="добавить">

</form>
</body>
</html>